### ISSUE TITLE
IE: Widget closes the popup on filter with Bootstrap CSS on page

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2300]
### Bug report
The DropDownList widget opened in IE11/Edge closes its popup on filter. Reported in ticket ID: 1067807

#### Replace the kendo all file with version later than 2016.3.914.

 #2178 fixed spontaneous closing of popup, however, issue remains with bootstrap on the page
 
1. Open [Dojo](http://dojo.telerik.com/urAmu/4)
1. Open the DropDown
1. Type a letter

### Current behavior

Popup closes

### Expected/desired behavior

Popup should close when the user selects value

### Environment

* **Kendo UI version:** 2016.3.1007
* **jQuery version:** v1.12.3
* **Browser:** [ IE 11 | Edge ]

**Comment by msereda** [comment]
Any chance this'll be fixed in the soon-to-come service pack?  I thought I'd look here before logging a telerik/kendo support ticket, as this bug is a fairly big issue for our current project.

**Comment by ggkrustev** [comment]
Guys, after a detailed research we found out that the issue is caused by the Bootstrap `body` styling.

The default margin is removed using bootstrap.css, which will break the popup positioning, hence the popup will be slightly mis-aligned. This will result in wider page with horizontal scrollbar. The IE will try to make scroll-into-view on popup open which will scroll the page, which unfortunately will force the popup close.

**The workaround for now is to revert the `body` styling**:

```
body {
    margin: 8;
    display: block;
}
```

http://dojo.telerik.com/urAmu/6

We will enhance the kendo popup to honor such global changes.

**Comment by dtopalov** [comment]
The discussed issue is still present if the DropDownList is in a modal window even when the workaround is used.

**Comment by kevld** [comment]
@ggkrustev your example ( http://dojo.telerik.com/urAmu/6 ) still not working
If it can help here is my installed version :
![image](https://cloud.githubusercontent.com/assets/13829079/19758235/7c1cdb9e-9c27-11e6-8d21-06105969c38e.png)

**Comment by ggkrustev** [comment]
@kevld it seems that the workaround works only in a slightly older IE11 (11.0.9600.17351).
If the workaround doesn't work for you then I would suggest you just wait for the fix to be released.

We will address it soon, but the fix probably will be included in Q1 2016.

**Comment by msereda** [comment]
Hi Georgi - just to clarify, it sounds like it won't be in the q3 sp and will be in q1 2017.  But it looks like you fixed the issue already.  Therefore, does that mean that if I wait for the next 'internal' build posted to the kendo site after the sp is released, the fix should be there?

Thanks.

**Comment by kevld** [comment]
@ggkrustev Great, thanks :)

**Comment by ggkrustev** [comment]
@msereda the fix is included only in our `master` branch which will be released in Q1 2017. The change that fixes this issue is subtle, but could break a lot of things. We want to test it further and if we believe that the fix is stable, we could release it in internal build too. I will update the thread.

**Comment by msereda** [comment]
Thanks for the info @ggkrustev.
