### ISSUE TITLE
The Grid's groupFooterTemplate during excel export is missing the fields.group data of all other fields

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-ui-core#3897]
### Bug report
While exporting to Excel, the Grid's groupFooterTemplate doesn't pass the e.fieldName.group object correctly if more that 1 aggregate is defined:

### Reproduction of the problem 1
Open the following dojo:
http://dojo.telerik.com/UTAsI/23

The group values of the grouped field will be logged in the console (e.name.group.value).
Clicking on the Export to Excel button will throw an error, because the group object will not be available

### Reproduction of the problem 2

Dojo: http://dojo.telerik.com/@bubblemaster/EXuYu

When in the grid, groupFooterTemplate: "#=data.fieldName.group.field # exists but in the Excel export it is passed as data.group.field which makes a condition in the groupFooterTemplate necessary.
```
groupFooterTemplate: "Count for #=data.ProductName.group ? data.ProductName.group.field : data.group.field #: #=count#"
```

### Environment

* **Kendo UI version:** 2017.3.1026

**Comment by mishoo** [comment]
The first sample works with latest code from master (we even [have it in playground](https://github.com/telerik/kendo/blob/master/playground/grid-group-footer-template-excel.html)).  It was fixed in this commit: https://github.com/telerik/kendo-ooxml/commit/e35afaafb8db4219b42aa405946df1c2e0e2539e

So I'm guessing the fix was just not yet released?

**Comment by matanasov** [comment]
@mishoo 
The playground example provided has only one aggregate. The issue is about 2 or more aggregates.
The dojo example in repo1 is updated to have 2 aggregates - try to export the grid - it won't because of JS error.
I have tested it locally with latest from master and it is still not fixed.

**Comment by Alex-Bubblemaster** [comment]
[Dojo](http://kendobuild-staging.openstack.progress.com/dojo-staging/ICoDaG) with latest version from staging

**Comment by mishoo** [comment]
This no longer reproduces with code from master, even with two aggregates.  ([tested in playground](https://github.com/telerik/kendo/blob/master/playground/grid-group-footer-template-excel.html)).  Closing it.

**Comment by Alex-Bubblemaster** [comment]
This is a matter of having consistent objects during the excel export so when people use the data aggregates object in the grid in the template that we provide, they are still valid during the export. The issue can be seen if the grid is grouped by month but in the template we are using the name.group.value (another field by which the grid is ***not*** grouped by). The data is available in the template but during export, it is not and it [raises an error](http://dojo.telerik.com/EzaSItEz).

- For comparison - the first image is the object available in the `groupFooterTemplate` , the second is the generated object during the export.

![image](https://user-images.githubusercontent.com/10980842/41770748-c0727414-761b-11e8-8206-93789a22b3dd.png)

Similar explanation can be found in #3095 & #3024
